name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python 3.x
#       uses: actions/setup-python@v2
#       with:
#         # Semantic version range syntax or exact version of a Python version
#         python-version: '3.x'
#         # Optional - x64 or x86 architecture, defaults to x64
#         architecture: 'x64'
      
#     - name: Install requirements
#       working-directory: chat
#       run: pip install -r requirements.txt
      
#     - name: Run Tests
#       working-directory: chat
#       run: python manage.py test
      
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
      
#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build and push Backend
#       uses: docker/build-push-action@v2
#       with:
#         context: chat
#         push: true
#         tags: scharykov/test_backend:latest

#     - name: Build and push Nginx
#       uses: docker/build-push-action@v2
#       with:
#         context: nginx
#         push: true
#         tags: scharykov/test_nginx:latest

#     - name: Build and push Frontend
#       uses: docker/build-push-action@v2
#       with:
#         context: front
#         push: true
#         tags: scharykov/test_frontend:latest
        
    - name: Deploy Backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: admin
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: | 
          docker-compose pull backend collect_static migration
          docker-compose rm -fs backend collect_static migration
          docker-compose up -d backend collect_static migration

    - name: Deploy Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: admin
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: | 
          docker-compose pull frontend
          docker-compose rm -fs frontend
          docker-compose up -d frontend

    - name: Deploy Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: admin
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: | 
          docker-compose pull nginx
          docker-compose rm -fs nginx
          docker-compose up -d nginx
